name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for the deployment environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm ci  # Install project dependencies

      - name: Build the application
        run: npm run build  # Run the build command (adjust if you use another build script)

      - name: Deploy to Render
        run: |
          curl -X POST https://render.com/deploy/some-deploy-hook-url  # Replace with your actual deploy hook URL
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Use Render API Key from GitHub Secrets
